spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_for_demo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pass

logging:
  level:
    com.example.demo: TRACE