spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_for_demo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pass

management:
  trace:
    http:
      enabled: true
  endpoints:
    web:
      exposure:
        include: httptrace

logging:
  level:
    com.example.multimodule: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: TRACE
    org.springframework.web: TRACE